import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { Providers } from "./providers";
import "@ant-design/v5-patch-for-react-19";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
       <Providers>
          <div className="w-full px-4 bg-white md:px-8 lg:px-16 xl:px-32 2xl:px-50">
              <NavBar />
          </div>
          <div className="px-4 bg-slate-100 md:px-8 lg:px-16 xl:px-32 2xl:px-50">
            {children}
          </div>
       </Providers>
      </body>
    </html>
  );
}
